# Generated by Django 5.0.4 on 2024-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servicoadicional_servico_servicos_adicionais'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('CPE', 'Consulta com médico Pediatra'), ('CCL', 'Consulta com médico Clínico'), ('COT', 'Consulta com médico Ortopedista')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='categoria_manutencao',
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria_Consulta',
            field=models.ManyToManyField(to='servicos.categoriaconsulta'),
        ),
        migrations.DeleteModel(
            name='CategoriaManutencao',
        ),
    ]
