# Generated by Django 5.1.7 on 2025-03-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_categoriaconsulta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='data_entrega',
            new_name='data_agendada',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='protocole',
        ),
        migrations.AddField(
            model_name='servico',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='servico',
            name='local',
            field=models.CharField(default='Local não informado', max_length=100),
        ),
    ]
