# Generated by Django 5.1.7 on 2025-03-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_rename_data_entrega_servico_data_agendada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='protocole',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
